tp2-laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/', 'PagesController');

Route::put('images/{id}','ImagesController@report');
Route::post('images/refresh/{image}', 'ImagesController@refresh');
Route::resource('images','ImagesController');

Route::resource('locations','LocationsController');
Route::delete('locations/destroy-loc/{id}', 'LocationsController@destroyLoc')->name('LocDestroy');
Route::delete('locations/destroy-loc-ajax/{id}', 'LocationsController@destroy')->name('LocDestroyAjax');

Auth::routes(['verify' => true]);

Route::get('/search', 'SearchController@index')->name('Search'); 
Route::get('/search/{request}', 'SearchController@index')->name('SearchAjax'); 
Route::get('/search-auto', 'SearchController@search')->name('SearchController.search');


Route::resource('user','UsersController');
Route::delete('user/destroy-account/{id}', 'UsersController@destroy_account')->name('UserDestroy');



Route::get ('dashboard', 'AdminsController@index')->name('dashboard');
Route::any ('reported', 'AdminsController@reportedList')->name('reported');
Route::delete('reported/clear', 'AdminsController@destroyAllReports');


// Route::middleware('admin')->group(function () {
//   Route::resource ('admin', 'AdminsController');
//   Route::resource ('user', 'UsersController');
// });

tp2-laravel/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex nofollow">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title> @yield('title','imager')</title>
    <!-- @yield('title','imager') -->

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
</head>
<body>    
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                     @yield('title','imager')
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="searchBar navbar-nav mr-auto">
                        @include('inc.input_search')
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}"><i class="fas fa-sign-in-alt"></i> {{ __('Connexion') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}"><i class="far fa-user-circle"></i> {{ __('Créer un compte') }}</a>
                                </li>
                            @endif
                        @else
                        <li class="nav-item">
                        <button type="button" class="btn btn-outline-warning" id="button-insert">Insérer une image</button>
                            </li>
                            <li class="nav-item dropdown pl-2">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                <i class="fas fa-user pr-2"></i> {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ url('user/'.Auth::user()->id).'/edit' }}">
                                        {{ __('Mon compte') }}                                    
                                    @admin
                                    <a class="dropdown-item" href="{{ route('dashboard') }}">
                                        {{ __('Tableau de bord') }}
                                    <a class="dropdown-item" href="{{ route('reported') }}">
                                     {{ __('Images signalées') }}
                                    </a>
                                    <a class="dropdown-item" href="{{ route('locations.index') }}">
                                        {{ __('Liste des lieux') }}
                                       </a>
                                    @endadmin
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Déconnexion') }}
                                    </a>

                         

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
        
            @include('inc.wrong')
            @include('inc.good')
            <!-- @if (session('status'))
                <div class="alert alert-success">
                    {{ session('status') }}
                </div>
            @endif -->

            @yield('content')
        </main>
    </div>
</body>
</html>